site_name: ICL RCS User Guide
theme:
  name: readthedocs
  highlightjs: true
plugins:
  - search
  - mkdocstrings:
      handlers:
        # See: https://mkdocstrings.github.io/python/usage/
        python:
          options:
            docstring_style: sphinx
markdown_extensions:
  - markdown_include.include:
      base_path: .
  - admonition
  - tables

nav:
  - Home: index.md
  - Remote Access: remoteaccess.md
  - Support and Training:
    - Getting Help: support/index.md
    - Attending a Clinic: support/attend-a-clinic.md
    - Citing the RCS: support/citing-rcs.md
  - HPC:
    - HPC at Imperial: hpc/index.md
    - Cluster Specification: hpc/cluster-specification.md
    - Getting Started:
      - Where to Start: hpc/getting-started/index.md
      - Using SSH: hpc/getting-started/using-ssh.md
      - Data Management: hpc/getting-started/data-management-on-hpc.md
      - Accessing Software: hpc/getting-started/accessing-software.md
      - Running your first job: hpc/getting-started/running-your-first-job.md
    - Queues:
      - Queueing: hpc/queues/index.md
      - Purpose of the Queuing System: hpc/queues/purpose-of-the-queue.md
      - How it works: hpc/queues/how-it-works.md
      - Classes of Jobs: hpc/queues/classes-of-jobs.md
      - Express Access: hpc/queues/express-access.md
      - Array Jobs: hpc/queues/array-jobs.md
      - Job Dependencies: hpc/queues/job-dependencies.md
      - Job Sizing Guidance: hpc/queues/job-sizing-guidance.md
      - MPI Jobs: hpc/queues/mpi-jobs.md
      - GPU Jobs: hpc/queues/gpu-jobs.md
      - Checkpointing: hpc/queues/checkpointing.md
    - Applications:
      - Loading Applications: hpc/applications/index.md
      - EasyBuild: hpc/applications/easybuild.md
      - Guides: 
        - Overview: hpc/applications/guides/index.md
        - Abaqus: hpc/applications/guides/abaqus.md
        - Conda: hpc/applications/guides/conda.md
        - Jupyter: hpc/applications/guides/jupyter.md
        - Lumerical: hpc/applications/guides/lumerical.md
        - Open OnDemand: hpc/applications/guides/openondemand.md
        - ORCA: hpc/applications/guides/orca.md
        - Python: hpc/applications/guides/python.md
        - R: hpc/applications/guides/R.md
    - Best Practice: hpc/best-practice.md
    - Pilot Systems:
      - HX1: hpc/pilot/hx1.md
      - CX3 Phase 2: hpc/pilot/cx3-phase2.md
  - RDS:
    - RDS: rds/index.md
    - RDS Paths: rds/paths.md
    - Accessing the RDS:
      - Overview: rds/access/index.md
      - Windows: rds/access/windows.md
      - macOS: rds/access/macos.md
      - Linux: rds/access/linux.md
    - Transferring Data:
      - Overview: rds/transferringdata/index.md
      - Globus: rds/transferringdata/globus.md
      - rsync and scp: rds/transferringdata/rsync-and-scp.md
    - Managing the RDS:
      - Disk Space: rds/managing/disk-space.md
      - Recovering Deleted Files: rds/managing/recovering-deleted-files.md

