site_name: ICL RCS User Guide
theme:
  name: readthedocs
  highlightjs: true
plugins:
  - search
  - mkdocstrings:
      handlers:
        # See: https://mkdocstrings.github.io/python/usage/
        python:
          options:
            docstring_style: sphinx
markdown_extensions:
  - markdown_include.include:
      base_path: .
  - admonition
  - tables

nav:
  - Home: index.md
  - HPC:
    - HPC at Imperial: hpc/index.md
    - Cluster Specification: hpc/cluster-specification.md
    - Getting Started:
      - Where to Start: hpc/getting-started/index.md
      - Using SSH: hpc/getting-started/using-ssh.md
      - Data Management: hpc/getting-started/data-management-on-hpc.md
      - Accessing Software: hpc/getting-started/accessing-software.md
      - Running your first job: hpc/getting-started/running-your-first-job.md
    - Queues:
      - Queueing: hpc/queues/index.md
      - Purpose of the Queuing System: hpc/queues/purpose-of-the-queue.md
      - How it works: hpc/queues/how-it-works.md
      - Classes of Jobs: hpc/queues/classes-of-jobs.md
      - Express Access: hpc/queues/express-access.md
      - Array Jobs: hpc/queues/array-jobs.md
      - Job Dependencies: hpc/queues/job-dependencies.md
      - Job Sizing Guidance: hpc/queues/job-sizing-guidance.md
      - MPI Jobs: hpc/queues/mpi-jobs.md
      - GPU Jobs: hpc/queues/gpu-jobs.md
      - Checkpointing: hpc/queues/checkpointing.md
    - Applications: hpc/applications/index.md
    - Best Practice: hpc/best-practice.md
  - RDS:
    - RDS: rds/index.md
  - Support and Training:
    - Getting Help: support/index.md
    - Attending a Clinic: support/attend-a-clinic.md
